POST http://localhost:8000/api/give/book
Content-Type: application/json

{
  "ISBN": "1234567890",
  "reader": {
    "id": 1,
    "name": "Фёдор",
    "surname": "Достоевский",
    "patronymic": "Михайлович"
  }
}
