POST http://localhost:8000/api/give/book
Content-Type: application/json

{
  "ISBN": "123456789",
  "reader": {
    "id": 1,
    "name": "Олег",
    "surname": "Иванов",
    "patronymic": "Михайлович"
  }
}
